// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/itempb/item-service.proto

package item_service_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetItemByIDRequest struct {
	ItemID               int32    `protobuf:"varint,1,opt,name=ItemID,proto3" json:"ItemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemByIDRequest) Reset()         { *m = GetItemByIDRequest{} }
func (m *GetItemByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetItemByIDRequest) ProtoMessage()    {}
func (*GetItemByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0738e7129d3319d0, []int{0}
}

func (m *GetItemByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemByIDRequest.Unmarshal(m, b)
}
func (m *GetItemByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetItemByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemByIDRequest.Merge(m, src)
}
func (m *GetItemByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetItemByIDRequest.Size(m)
}
func (m *GetItemByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemByIDRequest proto.InternalMessageInfo

func (m *GetItemByIDRequest) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

type ItemResponse struct {
	Cost                 float32  `protobuf:"fixed32,1,opt,name=Cost,proto3" json:"Cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemResponse) Reset()         { *m = ItemResponse{} }
func (m *ItemResponse) String() string { return proto.CompactTextString(m) }
func (*ItemResponse) ProtoMessage()    {}
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0738e7129d3319d0, []int{1}
}

func (m *ItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemResponse.Unmarshal(m, b)
}
func (m *ItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemResponse.Marshal(b, m, deterministic)
}
func (m *ItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemResponse.Merge(m, src)
}
func (m *ItemResponse) XXX_Size() int {
	return xxx_messageInfo_ItemResponse.Size(m)
}
func (m *ItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemResponse proto.InternalMessageInfo

func (m *ItemResponse) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func init() {
	proto.RegisterType((*GetItemByIDRequest)(nil), "services.item.GetItemByIDRequest")
	proto.RegisterType((*ItemResponse)(nil), "services.item.ItemResponse")
}

func init() { proto.RegisterFile("protos/itempb/item-service.proto", fileDescriptor_0738e7129d3319d0) }

var fileDescriptor_0738e7129d3319d0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0x2c, 0x49, 0xcd, 0x2d, 0x48, 0x02, 0x53, 0xba, 0xc5, 0xa9, 0x45, 0x65,
	0x99, 0xc9, 0xa9, 0x7a, 0x60, 0x29, 0x21, 0x5e, 0x28, 0xb7, 0x58, 0x0f, 0x24, 0xa9, 0xa4, 0xc3,
	0x25, 0xe4, 0x9e, 0x5a, 0xe2, 0x59, 0x92, 0x9a, 0xeb, 0x54, 0xe9, 0xe9, 0x12, 0x94, 0x5a, 0x58,
	0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc6, 0xc5, 0x06, 0x12, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0d, 0x82, 0xf2, 0x94, 0x94, 0xb8, 0x78, 0x40, 0xac, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc,
	0xe2, 0x54, 0x21, 0x21, 0x2e, 0x16, 0xe7, 0xfc, 0xe2, 0x12, 0xb0, 0x2a, 0xa6, 0x20, 0x30, 0xdb,
	0x28, 0x86, 0x8b, 0x1b, 0xa4, 0x26, 0x18, 0x62, 0x8d, 0x90, 0x2f, 0x17, 0x37, 0x92, 0x05, 0x42,
	0x8a, 0x7a, 0x28, 0xf6, 0xeb, 0x61, 0x5a, 0x2e, 0x25, 0x8d, 0xa6, 0x04, 0xd9, 0x46, 0x27, 0xc1,
	0x28, 0x7e, 0x54, 0x4f, 0x25, 0x25, 0xb1, 0x81, 0x3d, 0x66, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x64, 0x5b, 0x98, 0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	GetItemByID(ctx context.Context, in *GetItemByIDRequest, opts ...grpc.CallOption) (*ItemResponse, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) GetItemByID(ctx context.Context, in *GetItemByIDRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, "/services.item.ItemService/GetItemByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	GetItemByID(context.Context, *GetItemByIDRequest) (*ItemResponse, error)
}

// UnimplementedItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (*UnimplementedItemServiceServer) GetItemByID(ctx context.Context, req *GetItemByIDRequest) (*ItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemByID not implemented")
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_GetItemByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).GetItemByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.item.ItemService/GetItemByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).GetItemByID(ctx, req.(*GetItemByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.item.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItemByID",
			Handler:    _ItemService_GetItemByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/itempb/item-service.proto",
}
