// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/shippingpb/shipping-service.proto

package shipping_service_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalculateShippingCostRequest struct {
	Width                int32    `protobuf:"varint,1,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	Length               int32    `protobuf:"varint,3,opt,name=Length,proto3" json:"Length,omitempty"`
	Weight               int32    `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateShippingCostRequest) Reset()         { *m = CalculateShippingCostRequest{} }
func (m *CalculateShippingCostRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateShippingCostRequest) ProtoMessage()    {}
func (*CalculateShippingCostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_baa1fd7536ac8e34, []int{0}
}

func (m *CalculateShippingCostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateShippingCostRequest.Unmarshal(m, b)
}
func (m *CalculateShippingCostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateShippingCostRequest.Marshal(b, m, deterministic)
}
func (m *CalculateShippingCostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateShippingCostRequest.Merge(m, src)
}
func (m *CalculateShippingCostRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateShippingCostRequest.Size(m)
}
func (m *CalculateShippingCostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateShippingCostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateShippingCostRequest proto.InternalMessageInfo

func (m *CalculateShippingCostRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *CalculateShippingCostRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CalculateShippingCostRequest) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *CalculateShippingCostRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type CalculateShippingCostResponse struct {
	Cost                 float32  `protobuf:"fixed32,1,opt,name=Cost,proto3" json:"Cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateShippingCostResponse) Reset()         { *m = CalculateShippingCostResponse{} }
func (m *CalculateShippingCostResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateShippingCostResponse) ProtoMessage()    {}
func (*CalculateShippingCostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_baa1fd7536ac8e34, []int{1}
}

func (m *CalculateShippingCostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateShippingCostResponse.Unmarshal(m, b)
}
func (m *CalculateShippingCostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateShippingCostResponse.Marshal(b, m, deterministic)
}
func (m *CalculateShippingCostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateShippingCostResponse.Merge(m, src)
}
func (m *CalculateShippingCostResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateShippingCostResponse.Size(m)
}
func (m *CalculateShippingCostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateShippingCostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateShippingCostResponse proto.InternalMessageInfo

func (m *CalculateShippingCostResponse) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func init() {
	proto.RegisterType((*CalculateShippingCostRequest)(nil), "services.shipping.CalculateShippingCostRequest")
	proto.RegisterType((*CalculateShippingCostResponse)(nil), "services.shipping.CalculateShippingCostResponse")
}

func init() {
	proto.RegisterFile("protos/shippingpb/shipping-service.proto", fileDescriptor_baa1fd7536ac8e34)
}

var fileDescriptor_baa1fd7536ac8e34 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0xce, 0xc8, 0x2c, 0x28, 0xc8, 0xcc, 0x4b, 0x2f, 0x48, 0x82, 0x33, 0x75,
	0x8b, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0xf5, 0xc0, 0x4a, 0x84, 0x04, 0xa1, 0xdc, 0x62, 0x3d,
	0x98, 0x02, 0xa5, 0x1a, 0x2e, 0x19, 0xe7, 0xc4, 0x9c, 0xe4, 0xd2, 0x9c, 0xc4, 0x92, 0xd4, 0x60,
	0xa8, 0xa0, 0x73, 0x7e, 0x71, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x08, 0x17,
	0x6b, 0x78, 0x66, 0x4a, 0x49, 0x86, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x84, 0x23, 0x24,
	0xc6, 0xc5, 0xe6, 0x91, 0x9a, 0x99, 0x9e, 0x51, 0x22, 0xc1, 0x04, 0x16, 0x86, 0xf2, 0x40, 0xe2,
	0x3e, 0xa9, 0x79, 0xe9, 0x25, 0x19, 0x12, 0xcc, 0x10, 0x71, 0x08, 0x0f, 0x24, 0x1e, 0x0e, 0x51,
	0xcf, 0x02, 0x11, 0x87, 0xf0, 0x94, 0x8c, 0xb9, 0x64, 0x71, 0xd8, 0x5e, 0x5c, 0x90, 0x9f, 0x57,
	0x9c, 0x2a, 0x24, 0xc4, 0xc5, 0x02, 0xe2, 0x83, 0x6d, 0x67, 0x0a, 0x02, 0xb3, 0x8d, 0x7a, 0x19,
	0xb9, 0xf8, 0x61, 0x8a, 0x83, 0x21, 0x1e, 0x12, 0xaa, 0xe2, 0x12, 0xc5, 0x6a, 0x90, 0x90, 0xbe,
	0x1e, 0x86, 0x9f, 0xf5, 0xf0, 0x79, 0x58, 0xca, 0x80, 0x78, 0x0d, 0x10, 0x37, 0x3a, 0x89, 0x46,
	0x09, 0x63, 0x86, 0x77, 0x52, 0x12, 0x1b, 0x38, 0xcc, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x6a, 0x54, 0x1b, 0x78, 0x9f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShippingServiceClient is the client API for ShippingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShippingServiceClient interface {
	CalculateShippingCost(ctx context.Context, in *CalculateShippingCostRequest, opts ...grpc.CallOption) (*CalculateShippingCostResponse, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CalculateShippingCost(ctx context.Context, in *CalculateShippingCostRequest, opts ...grpc.CallOption) (*CalculateShippingCostResponse, error) {
	out := new(CalculateShippingCostResponse)
	err := c.cc.Invoke(ctx, "/services.shipping.ShippingService/CalculateShippingCost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShippingServiceServer is the server API for ShippingService service.
type ShippingServiceServer interface {
	CalculateShippingCost(context.Context, *CalculateShippingCostRequest) (*CalculateShippingCostResponse, error)
}

// UnimplementedShippingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShippingServiceServer struct {
}

func (*UnimplementedShippingServiceServer) CalculateShippingCost(ctx context.Context, req *CalculateShippingCostRequest) (*CalculateShippingCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateShippingCost not implemented")
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_CalculateShippingCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateShippingCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CalculateShippingCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.shipping.ShippingService/CalculateShippingCost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CalculateShippingCost(ctx, req.(*CalculateShippingCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.shipping.ShippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateShippingCost",
			Handler:    _ShippingService_CalculateShippingCost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/shippingpb/shipping-service.proto",
}
